### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by BubbatheVTOG** [BubbatheVTOG/ISTE_240_Group_Project#39]
- [x] Navigation needs to show where on the site the user is.
 - [x] Navigation needs to have some sort of style for when it gets active and shows sub menus. 
- [x] Apply some sort of transition to the menus expanding. 
- [x] Menu stays expanded if user is on one of the subpages of a section.
- [x] color highlighting the current section that a person is on. 
- [x] We also need to make sure the menu stays expanded if the user is on one of the pages (eg if they are on introduction they should be able to see introduction in the nav).
- [x] Set the scrollbar policy to either `overflow: hidden;` OR change the look of it [using this technique](https://www.w3schools.com/howto/howto_css_custom_scrollbar.asp).

**Comment by justein230** [comment]
We also need to make sure the menu stays expanded if the user is on one of the pages (eg if they are on introduction they should be able to see introduction in the nav.

**Comment by BubbatheVTOG** [comment]
@justein230 added to the list.

**Comment by BubbatheVTOG** [comment]
For the issue of making the menus stay expanded. Clare suggested we use `document.location` to get the current url, then parse that string for the location, then use that to set `clicked` on the checkbox (which makes it expand).

**Comment by justein230** [comment]
@BubbatheVTOG I can do the parsing in JS, I do a similar thing in my personal project.

**Comment by BubbatheVTOG** [comment]
This issue was officially closed by @pxc9659
