### ISSUE TITLE
Navigation CSS needs drastic REFACTOR

### ISSUE THREAD

**Issue by BubbatheVTOG** [BubbatheVTOG/ISTE_240_Group_Project#47]
Currently there is a lot of duplicate code between the css for mobile and css for desktop in regards to the navigation. This is bad practice.

**Comment by justein230** [comment]
It really doesn't matter, I don't think that affects our grade that much. It's also what happens when there are multiple people working on a file. This shouldn't be labeled as critical, if everything works it works.
