### ISSUE TITLE
Quiz JavaScript throws error.

### ISSUE THREAD

**Issue by justein230** [BubbatheVTOG/ISTE_240_Group_Project#71]
After quick StackOverflow search, something to do with jQuery not being available. Issue is on line 74 of quiz.js.

`Uncaught ReferenceError: $ is not defined
    at quiz.js:74`

**Comment by BubbatheVTOG** [comment]
I reviewed this code further and I believe it is because @Vignesh111 added ajax code to the bottom of the quiz javascript file.
