### ISSUE TITLE
How to get to the terminal section - Add terminal.php to comman line intro

### ISSUE THREAD

**Issue by BubbatheVTOG** [BubbatheVTOG/ISTE_240_Group_Project#81]

**Comment by justein230** [comment]
We should get the rest of our content done first. Maybe @630848886 could take care of it.

**Comment by 630848886** [comment]
I will do it on this weekend, because I have 3 exam on the week. Is that ok?

**Comment by BubbatheVTOG** [comment]
sure, @630848886 that's fine. You do have a very important 121 exam this week ;).

**Comment by justein230** [comment]
@630848886 have you started this?

**Comment by 630848886** [comment]
not yet, I'm working for the individual now,  I will work it on Friday night

**Comment by BubbatheVTOG** [comment]
This issue is part of #112

**Comment by pxc9659** [comment]
Created a php file that needs to be included in the command line intro
